/* cnetc.library prototypes */
void						Private1(void);
struct CNetCContext	*CNC_InitContext(char *cport_a1);
void 						CNC_DisposeContext(void);
void 						CNC_CallHost(UBYTE c);
void 						CNC_PutText(char *text);
void						CNC_PutA(void);
void						CNC_ShutDown(char *spawn);
int						CNC_EnterLine(UBYTE len, ULONG flags, char *prompt);
char						CNC_OneKey(void);
void						CNC_EnterPassword(UBYTE len);
long						CNC_CommonCommands(void);
UBYTE 					CNC_ReadFile(char *file, UBYTE flags);
void						CNC_SetDoing(char *what);
void						CNC_CallEditor(short max, short inlines);
UBYTE 					CNC_ReadGraphics(char *path, char flags);
void						CNC_MakeDate(struct IsDate *date, char *output);
UBYTE						CNC_ReadAccount(short id, struct UserData *udata);
UBYTE						CNC_SaveAccount(struct UserData *udata, short id);
UBYTE						CNC_AddCharge(short n, short a);
UBYTE						CNC_CheckBalance(short n, short a);
int						CNC_EnterText(char firstchar, short maxchars, short perline, short maxlines);
long						CNC_ConferenceWait(short a);
void						CNC_CheckChanges(void);
long						CNC_ConvertAccess(char *s);
long						CNC_GetFree(char *name, UBYTE quiet, char *deststring, char **bm);
short						CNC_FindAccount(char *a, struct UserData *b, UBYTE c);
void						CNC_CheckFlowControl(void);
long						CNC_ListDir(UBYTE a, UBYTE b, struct IsDate *c);
UBYTE						CNC_Rnext(void);
void						CNC_ParseCommandLine(UBYTE numargs);
short						CNC_FindCommand(short num);
void						CNC_ReadMessagePoint(char *a, long b);
void						CNC_EditMessage(char *file);
void						CNC_LoadText(BPTR fh);
char						CNC_WaitForInput(long mics);
UBYTE						CNC_SelectAndDownload(char *file, UBYTE flags);
short						CNC_VisualDataEditor(char *file, void *data, long size);
void						CNC_ExtSetMinFree(long free);
UBYTE						CNC_ExtSetProtocol(char a);
char 						*CNC_ExtDownload(char *args);
char 						*CNC_ExtUpload(char *args);
UBYTE						CNC_PutQ(char *a);
void						CNC_DoReturn(void);
BYTE						CNC_WriteUKeys(BYTE getsem);
void						CNC_DoANSI(UBYTE n, USHORT a, USHORT b);
void						CNC_DoANSIOut(UBYTE n);
BYTE						CNC_InputSignalInit(char *portname, ULONG timeout);
void						CNC_InputSignalDispose(void);
void						CNC_OWriteLog( short n, char *text1, char *text2 );
void 						CNC_VDEapply( void *data0, void *data1 );
void						CNC_VDEclose( void );
long						CNC_EnterAccess( char *prompt, long def );
UBYTE						CNC_CheckCarrier( void );
char						CNC_CheckOLM( void );
void						CNC_JMakeDate( struct IsDate *date, char *output );
long						CNC_GrabFileSize( UBYTE quiet );
void						CNC_SaveUser( struct UserData *user, short id );
void 						CNC_MailSend( short account );
UBYTE						CNC_PutQMult( char *prompt, char *poss);
void 						CNC_ReadLog( char *logname );
void 						CNC_OpenDisplay( short portnum );
void	 					CNC_GetSetFileNote( char *pathfile);
UBYTE 					CNC_ExtractFile( char *pathfile);
void                 CNC_DLoadSelect( UBYTE optdel );
short                CNC_FindForeignArea( char *gokey );
void                 CNC_OutScan( void );
