// Prototypes for functions in cnetcdoor.lib

BYTE  CWriteUKeys           ( BYTE getsem );
char  *CExtDownload         ( char *args );
char  *CExtUpload           ( char *args );
char  CCheckOLM             ( void );
char  COneKey               ( void );
char  CWaitForInput         ( long mics );
int   CEnterLine            ( UBYTE len, ULONG flags, char *prompt );
int   CEnterText            ( char firstchar, short maxchars, short perline, short maxlines );
long  CCommonCommands       ( void );
long  CConferenceWait       ( short a );
long  CConvertAccess        ( char *s );
long  CEnterAccess          ( char *prompt, long def );
long  CGetFree              ( char *s, UBYTE q );
long  CGrabFileSize         ( UBYTE quiet );
long  CListDir              ( UBYTE a, UBYTE b, struct IsDate *c );
short CFindAccount          ( char *a, struct UserData *b, UBYTE quiet );
short CFindCommand          ( short num );
short CVisualDataEditor     ( char *file, void *data, long size );
UBYTE CAddCharge            ( short n, short a );
UBYTE CCheckBalance         ( short n, short a );
UBYTE CExtSetProtocol       ( char a );
UBYTE CPutQ                 ( char *a );
UBYTE CReadAccount          ( short id, struct UserData *user );
UBYTE CReadFile             ( char *path, UBYTE flags );
UBYTE CReadGraphics         ( char *path, char flags );
UBYTE CRnext                ( void );
UBYTE CSaveAccount          ( struct UserData *user, short id );
UBYTE CSelectAndDownload    ( char *file, UBYTE flags );
void  CCallEditor           ( short max, short inlines );
void  CallHost              ( UBYTE c );
void  CCheckChanges         ( void );
void  CCheckFlowControl     ( void );
void  CDoANSI               ( UBYTE n, USHORT a, USHORT b);
void  CDoANSIOut            ( UBYTE n);
void  CDoReturn             ( void );
void  CEditMessage          ( char *file );
void  CEnterPassword        ( UBYTE len );
void  CExtSetMinFree        ( long free );
void  CLoadError            ( void );
void  CLoadText             ( BPTR fh );
void  CMakeDate             ( struct IsDate *date, char *output );
void  CMakeEd               ( char *path );
void  CParseCommandLine     ( UBYTE numargs );
void  CPutA                 ( void );
void  CPutText              ( char *text );
void  CReadMessagePoint     ( char *a, long b );
void  CSaveUser             ( struct UserData *user, short id );
void  CSetDoing             ( char *what );
void  CShutDown             ( char *spawn );
void  CVDEapply             ( void *data0, void *data1 );
void  CVDEclose             ( void );
void  COWriteLog            ( short n, char *text1, char *text2 );
UBYTE CPutQMult             ( char *prompt, char *poss);
UBYTE CCheckCarrier         ( void );
