/* CNetC Shared Library */
/*pragma libcall CNetCBase Private1 1e 0*/
#pragma libcall CNetCBase CNC_InitContext 24 901
#pragma libcall CNetCBase CNC_DisposeContext 2a 0
#pragma libcall CNetCBase CNC_CallHost 30 101
#pragma libcall CNetCBase CNC_PutText 36 901
#pragma libcall CNetCBase CNC_PutA 3c 0
#pragma libcall CNetCBase CNC_ShutDown 42 901
#pragma libcall CNetCBase CNC_EnterLine 48 92103
#pragma libcall CNetCBase CNC_OneKey 4e 0
#pragma libcall CNetCBase CNC_EnterPassword 54 101
#pragma libcall CNetCBase CNC_CommonCommands 5a 0
#pragma libcall CNetCBase CNC_ReadFile 60 1902
#pragma libcall CNetCBase CNC_SetDoing 66 901
#pragma libcall CNetCBase CNC_CallEditor 6c 2102
#pragma libcall CNetCBase CNC_ReadGraphics 72 1902
#pragma libcall CNetCBase CNC_MakeDate 78 A902
#pragma libcall CNetCBase CNC_ReadAccount 7e 9102
#pragma libcall CNetCBase CNC_SaveAccount 84 1902
#pragma libcall CNetCBase CNC_AddCharge 8a 2102
#pragma libcall CNetCBase CNC_CheckBalance 90 2102
#pragma libcall CNetCBase CNC_EnterText 96 432104
#pragma libcall CNetCBase CNC_ConferenceWait 9c 101
#pragma libcall CNetCBase CNC_CheckChanges a2 0
#pragma libcall CNetCBase CNC_ConvertAccess a8 901
#pragma libcall CNetCBase CNC_GetFree ae BA1904
#pragma libcall CNetCBase CNC_FindAccount b4 1A903
#pragma libcall CNetCBase CNC_CheckFlowControl ba 0
#pragma libcall CNetCBase CNC_ListDir c0 92103
#pragma libcall CNetCBase CNC_Rnext c6 0
#pragma libcall CNetCBase CNC_ParseCommandLine cc 101
#pragma libcall CNetCBase CNC_FindCommand d2 101
#pragma libcall CNetCBase CNC_ReadMessagePoint d8 1902
#pragma libcall CNetCBase CNC_EditMessage de 901
#pragma libcall CNetCBase CNC_LoadText e4 901
#pragma libcall CNetCBase CNC_WaitForInput ea 101
#pragma libcall CNetCBase CNC_SelectAndDownload f0 1902
#pragma libcall CNetCBase CNC_VisualDataEditor f6 1A903
#pragma libcall CNetCBase CNC_ExtSetMinFree fc 101
#pragma libcall CNetCBase CNC_ExtSetProtocol 102 101
#pragma libcall CNetCBase CNC_ExtDownload 108 901
#pragma libcall CNetCBase CNC_ExtUpload 10e 901
#pragma libcall CNetCBase CNC_PutQ 114 901
#pragma libcall CNetCBase CNC_DoReturn 11a 0
#pragma libcall CNetCBase CNC_WriteUKeys 120 101
#pragma libcall CNetCBase CNC_DoANSI 126 32103
#pragma libcall CNetCBase CNC_DoANSIOut 12c 101
#pragma libcall CNetCBase CNC_InputSignalInit 132 1902
#pragma libcall CNetCBase CNC_InputSignalDispose 138 0
#pragma libcall CNetCBase CNC_OWriteLog 13e A9103
#pragma libcall CNetCBase CNC_VDEapply 144 A902
#pragma libcall CNetCBase CNC_VDEclose 14a 0
#pragma libcall CNetCBase CNC_EnterAccess 150 1902
#pragma libcall CNetCBase CNC_CheckCarrier 156 0
#pragma libcall CNetCBase CNC_CheckOLM 15c 0
#pragma libcall CNetCBase CNC_JMakeDate 162 A902
#pragma libcall CNetCBase CNC_GrabFileSize 168 101
#pragma libcall CNetCBase CNC_SaveUser 16e 1902
#pragma libcall CNetCBase CNC_PutQMult 174 A902
#pragma libcall CNetCBase CNC_MailSend 17a 101
#pragma libcall CNetCBase CNC_ReadLog 180 901
#pragma libcall CNetCBase CNC_OpenDisplay 186 101
#pragma libcall CNetCBase CNC_GetSetFileNote 18c 901
#pragma libcall CNetCBase CNC_ExtractFile 192 901
#pragma libcall CNetCBase CNC_DLoadSelect 198 101
#pragma libcall CNetCBase CNC_FindForeignArea 19e 901
#pragma libcall CNetCBase CNC_OutScan 1a4 0
