
#ifndef CNET_BBSTEXTINFO
#define CNET_BBSTEXTINFO

#define BM_BBSLIST_DLPROMPT     1596
#define BM_BBSLIST_PACKLINE     1597
#define BM_BBSLIST_ENTRY        1607
#define BM_BBSLIST_NUMSYS       1608
#define BM_BBSLIST_DOING        1609
#define BM_BBSLIST_PROMPT       1610
#define BM_BBSLIST_QUIT         1612
#define BM_BBSLIST_NUMPROMPT    1614
#define BM_BBSLIST_LISTHEADER   1616
#define BM_BBSLIST_LISTFORMAT   1617
#define BM_BBSLIST_LISTCOMMENT  1618
#define BM_BBSLIST_LISTFOOTER   1620

#endif
