#ifndef CNET_CRON_H
#define CNET_CRON_H

/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_Events_LVGad                        0
#define GD_EventName_Gad                       1
#define GD_Command_Gad                         2
#define GD_Ports_Gad                           3
#define GD_Hour_Gad                            4
#define GD_Minute_Gad                          5
#define GD_EventTypes_LVGad                    6
#define GD_Gadget70                            7
#define GD_Valid_Gad                           8
#define GD_Sunday_Gad                          9
#define GD_Monday_Gad                          10
#define GD_Tuesday_Gad                         11
#define GD_Wednesday_Gad                       12
#define GD_Thursday_Gad                        13
#define GD_Friday_Gad                          14
#define GD_Saturday_Gad                        15
#define GD_Invoke_Gad                          16
#define GD_NewEvent_Gad                        17
#define GD_AddEvent_Gad                        18
#define GD_DeleteEvent_Gad                     19

#define GDX_Events_LVGad                       0
#define GDX_EventName_Gad                      1
#define GDX_Command_Gad                        2
#define GDX_Ports_Gad                          3
#define GDX_Hour_Gad                           4
#define GDX_Minute_Gad                         5
#define GDX_EventTypes_LVGad                   6
#define GDX_Gadget70                           7
#define GDX_Valid_Gad                          8
#define GDX_Sunday_Gad                         9
#define GDX_Monday_Gad                         10
#define GDX_Tuesday_Gad                        11
#define GDX_Wednesday_Gad                      12
#define GDX_Thursday_Gad                       13
#define GDX_Friday_Gad                         14
#define GDX_Saturday_Gad                       15
#define GDX_Invoke_Gad                         16
#define GDX_NewEvent_Gad                       17
#define GDX_AddEvent_Gad                       18
#define GDX_DeleteEvent_Gad                    19

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *Project0Wnd;
extern struct Gadget        *Project0GList;
extern struct Gadget        *Project0Gadgets[20];
extern UWORD                 Project0Left;
extern UWORD                 Project0Top;
extern UWORD                 Project0Width;
extern UWORD                 Project0Height;
extern UBYTE                *Project0Wdt;
extern UBYTE                *Invoke_Gad0Labels[];
extern struct MinList        EventTypes_LVGad0List;
extern struct TextAttr       XCourier13;
extern UWORD                 Project0GTypes[];
extern struct NewGadget      Project0NGad[];
extern ULONG                 Project0GTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int OpenProject0Window( void );
extern void CloseProject0Window( void );

#endif /* CNET_CRON_H */
